version: '3.8'

services:
  qr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    restart: unless-stopped
